<?php
// Automatically Generated by TestLink Installer - Thu, 09 Sep 21 14:11:23 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'abc123');
define('DB_HOST', 'db');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
